
services:
  linkshort:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linkshort
    logging:
      driver: syslog
      options:
        tag: foo-logs
    ports:
      - "5001:5001"
      - "40001:40001"
    volumes:
      - ./config/main.yml:/app/config/main.yml
      - ./config/database.yml:/app/config/database.yml

  postgres:
    container_name: PostgresInfo
    image: postgres:latest
    environment:
      - POSTGRES_USER=matroskin
      - POSTGRES_PASSWORD=74tbr6r54f78
    ports:
      - "5435:5435"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U matroskin" ]
      interval: 5s
      timeout: 105s
      retries: 5

  redis:
    container_name: RedisInfo
    image: redis:latest
    restart: always
    ports:
      - "6382:6382"
    environment:
      - REDIS_PORT=6382
      - REDIS_DATABASES=16
