// Code generated by MockGen. DO NOT EDIT.
// Source: linkShortOzon/internals/linkShort/orm (interfaces: LinkShortWrapperInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLinkShortWrapperInterface is a mock of LinkShortWrapperInterface interface.
type MockLinkShortWrapperInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLinkShortWrapperInterfaceMockRecorder
}

// MockLinkShortWrapperInterfaceMockRecorder is the mock recorder for MockLinkShortWrapperInterface.
type MockLinkShortWrapperInterfaceMockRecorder struct {
	mock *MockLinkShortWrapperInterface
}

// NewMockLinkShortWrapperInterface creates a new mock instance.
func NewMockLinkShortWrapperInterface(ctrl *gomock.Controller) *MockLinkShortWrapperInterface {
	mock := &MockLinkShortWrapperInterface{ctrl: ctrl}
	mock.recorder = &MockLinkShortWrapperInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkShortWrapperInterface) EXPECT() *MockLinkShortWrapperInterfaceMockRecorder {
	return m.recorder
}

// CreateLinkShort mocks base method.
func (m *MockLinkShortWrapperInterface) CreateLinkShort(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLinkShort", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLinkShort indicates an expected call of CreateLinkShort.
func (mr *MockLinkShortWrapperInterfaceMockRecorder) CreateLinkShort(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLinkShort", reflect.TypeOf((*MockLinkShortWrapperInterface)(nil).CreateLinkShort), arg0, arg1)
}

// CreateLinkShortPostgres mocks base method.
func (m *MockLinkShortWrapperInterface) CreateLinkShortPostgres(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLinkShortPostgres", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLinkShortPostgres indicates an expected call of CreateLinkShortPostgres.
func (mr *MockLinkShortWrapperInterfaceMockRecorder) CreateLinkShortPostgres(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLinkShortPostgres", reflect.TypeOf((*MockLinkShortWrapperInterface)(nil).CreateLinkShortPostgres), arg0, arg1)
}

// CreateLinkShortRedis mocks base method.
func (m *MockLinkShortWrapperInterface) CreateLinkShortRedis(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLinkShortRedis", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLinkShortRedis indicates an expected call of CreateLinkShortRedis.
func (mr *MockLinkShortWrapperInterfaceMockRecorder) CreateLinkShortRedis(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLinkShortRedis", reflect.TypeOf((*MockLinkShortWrapperInterface)(nil).CreateLinkShortRedis), arg0, arg1)
}

// TakeLinkFull mocks base method.
func (m *MockLinkShortWrapperInterface) TakeLinkFull(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TakeLinkFull", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TakeLinkFull indicates an expected call of TakeLinkFull.
func (mr *MockLinkShortWrapperInterfaceMockRecorder) TakeLinkFull(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TakeLinkFull", reflect.TypeOf((*MockLinkShortWrapperInterface)(nil).TakeLinkFull), arg0)
}

// TakeLinkFullPostgres mocks base method.
func (m *MockLinkShortWrapperInterface) TakeLinkFullPostgres(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TakeLinkFullPostgres", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TakeLinkFullPostgres indicates an expected call of TakeLinkFullPostgres.
func (mr *MockLinkShortWrapperInterfaceMockRecorder) TakeLinkFullPostgres(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TakeLinkFullPostgres", reflect.TypeOf((*MockLinkShortWrapperInterface)(nil).TakeLinkFullPostgres), arg0)
}

// TakeLinkFullRedis mocks base method.
func (m *MockLinkShortWrapperInterface) TakeLinkFullRedis(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TakeLinkFullRedis", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TakeLinkFullRedis indicates an expected call of TakeLinkFullRedis.
func (mr *MockLinkShortWrapperInterfaceMockRecorder) TakeLinkFullRedis(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TakeLinkFullRedis", reflect.TypeOf((*MockLinkShortWrapperInterface)(nil).TakeLinkFullRedis), arg0)
}
