// Code generated by MockGen. DO NOT EDIT.
// Source: linkShortOzon/internals/linkShort/application (interfaces: LinkShortAppInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLinkShortAppInterface is a mock of LinkShortAppInterface interface.
type MockLinkShortAppInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLinkShortAppInterfaceMockRecorder
}

// MockLinkShortAppInterfaceMockRecorder is the mock recorder for MockLinkShortAppInterface.
type MockLinkShortAppInterfaceMockRecorder struct {
	mock *MockLinkShortAppInterface
}

// NewMockLinkShortAppInterface creates a new mock instance.
func NewMockLinkShortAppInterface(ctrl *gomock.Controller) *MockLinkShortAppInterface {
	mock := &MockLinkShortAppInterface{ctrl: ctrl}
	mock.recorder = &MockLinkShortAppInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkShortAppInterface) EXPECT() *MockLinkShortAppInterfaceMockRecorder {
	return m.recorder
}

// CreateLinkShortApp mocks base method.
func (m *MockLinkShortAppInterface) CreateLinkShortApp(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLinkShortApp", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLinkShortApp indicates an expected call of CreateLinkShortApp.
func (mr *MockLinkShortAppInterfaceMockRecorder) CreateLinkShortApp(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLinkShortApp", reflect.TypeOf((*MockLinkShortAppInterface)(nil).CreateLinkShortApp), arg0)
}

// TakeLinkFullApp mocks base method.
func (m *MockLinkShortAppInterface) TakeLinkFullApp(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TakeLinkFullApp", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TakeLinkFullApp indicates an expected call of TakeLinkFullApp.
func (mr *MockLinkShortAppInterfaceMockRecorder) TakeLinkFullApp(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TakeLinkFullApp", reflect.TypeOf((*MockLinkShortAppInterface)(nil).TakeLinkFullApp), arg0)
}
