// Code generated by MockGen. DO NOT EDIT.
// Source: linkShortOzon/internals/myerror (interfaces: CheckErrorInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCheckErrorInterface is a mock of CheckErrorInterface interface.
type MockCheckErrorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCheckErrorInterfaceMockRecorder
}

// MockCheckErrorInterfaceMockRecorder is the mock recorder for MockCheckErrorInterface.
type MockCheckErrorInterfaceMockRecorder struct {
	mock *MockCheckErrorInterface
}

// NewMockCheckErrorInterface creates a new mock instance.
func NewMockCheckErrorInterface(ctrl *gomock.Controller) *MockCheckErrorInterface {
	mock := &MockCheckErrorInterface{ctrl: ctrl}
	mock.recorder = &MockCheckErrorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckErrorInterface) EXPECT() *MockCheckErrorInterfaceMockRecorder {
	return m.recorder
}

// CheckErrorCreateLinkShort mocks base method.
func (m *MockCheckErrorInterface) CheckErrorCreateLinkShort(arg0 error) (error, []byte, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckErrorCreateLinkShort", arg0)
	ret0, _ := ret[0].(error)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(int)
	return ret0, ret1, ret2
}

// CheckErrorCreateLinkShort indicates an expected call of CheckErrorCreateLinkShort.
func (mr *MockCheckErrorInterfaceMockRecorder) CheckErrorCreateLinkShort(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckErrorCreateLinkShort", reflect.TypeOf((*MockCheckErrorInterface)(nil).CheckErrorCreateLinkShort), arg0)
}

// CheckErrorCreateLinkShortGrpc mocks base method.
func (m *MockCheckErrorInterface) CheckErrorCreateLinkShortGrpc(arg0 error) (error, string, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckErrorCreateLinkShortGrpc", arg0)
	ret0, _ := ret[0].(error)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(int)
	return ret0, ret1, ret2
}

// CheckErrorCreateLinkShortGrpc indicates an expected call of CheckErrorCreateLinkShortGrpc.
func (mr *MockCheckErrorInterfaceMockRecorder) CheckErrorCreateLinkShortGrpc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckErrorCreateLinkShortGrpc", reflect.TypeOf((*MockCheckErrorInterface)(nil).CheckErrorCreateLinkShortGrpc), arg0)
}

// CheckErrorTakeLinkFull mocks base method.
func (m *MockCheckErrorInterface) CheckErrorTakeLinkFull(arg0 error) (error, []byte, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckErrorTakeLinkFull", arg0)
	ret0, _ := ret[0].(error)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(int)
	return ret0, ret1, ret2
}

// CheckErrorTakeLinkFull indicates an expected call of CheckErrorTakeLinkFull.
func (mr *MockCheckErrorInterfaceMockRecorder) CheckErrorTakeLinkFull(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckErrorTakeLinkFull", reflect.TypeOf((*MockCheckErrorInterface)(nil).CheckErrorTakeLinkFull), arg0)
}

// CheckErrorTakeLinkFullGrpc mocks base method.
func (m *MockCheckErrorInterface) CheckErrorTakeLinkFullGrpc(arg0 error) (error, string, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckErrorTakeLinkFullGrpc", arg0)
	ret0, _ := ret[0].(error)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(int)
	return ret0, ret1, ret2
}

// CheckErrorTakeLinkFullGrpc indicates an expected call of CheckErrorTakeLinkFullGrpc.
func (mr *MockCheckErrorInterfaceMockRecorder) CheckErrorTakeLinkFullGrpc(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckErrorTakeLinkFullGrpc", reflect.TypeOf((*MockCheckErrorInterface)(nil).CheckErrorTakeLinkFullGrpc), arg0)
}

// SetRequestIdUser mocks base method.
func (m *MockCheckErrorInterface) SetRequestIdUser(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRequestIdUser", arg0)
}

// SetRequestIdUser indicates an expected call of SetRequestIdUser.
func (mr *MockCheckErrorInterfaceMockRecorder) SetRequestIdUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRequestIdUser", reflect.TypeOf((*MockCheckErrorInterface)(nil).SetRequestIdUser), arg0)
}
