db_postgres:
  host: BackInfo
  port: 5432
  username: matroskin
  password: 74tbr6r54f
  schemaname: postgres

db_redis:
  host: RedisInfo
  port: 6382
  network: tcp
  password: p@ss$12E45
#  password: p@ss$12E45
