name: Docker Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
          cache: false
      - name: Vendor
        run: go mod vendor
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          skip-build-cache: true
          skip-pkg-cache: true

  tests:
    name: tests
    runs-on: ubuntu-latest
    needs: golangci-lint
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run test
        run: |
          go mod vendor
          make test

  build:
    runs-on: ubuntu-latest
    needs: [tests, golangci-lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - name: add go.sum
        run: go mod tidy
      - name: Login to Docker Hub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push linkShort
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: matros71239/linkshort:latest
